"""Add DisplayedThreat model for synthetic threat tracking

Revision ID: 64bc13fab0c0
Revises: add_block_token
Create Date: 2026-02-14 18:29:43.372590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64bc13fab0c0'
down_revision = 'add_block_token'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_poll', sa.DateTime(), nullable=True),
    sa.Column('last_ip', sa.String(length=45), nullable=True),
    sa.Column('last_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_agent_id'), ['agent_id'], unique=True)

    op.create_table('agent_enforcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_enforcement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_enforcement_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_enforcement_ip_address'), ['ip_address'], unique=False)

    op.create_table('displayed_threat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threat_id', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('threat_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('detection_time', sa.DateTime(), nullable=False),
    sa.Column('displayed_at', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('displayed_threat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_displayed_threat_displayed_at'), ['displayed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_displayed_threat_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_displayed_threat_reported_at'), ['reported_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_displayed_threat_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_displayed_threat_threat_id'), ['threat_id'], unique=True)

    with op.batch_alter_table('access_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_request_created_at'))

    op.drop_table('access_request')
    op.drop_table('threat_notification')
    with op.batch_alter_table('block_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_block_token_token'))
        batch_op.create_index(batch_op.f('ix_block_token_token'), ['token'], unique=True)

    with op.batch_alter_table('blocked_threat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocked_threat_blocked_at'), ['blocked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocked_threat_ip_address'), ['ip_address'], unique=False)

    with op.batch_alter_table('threat_action_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'blocked_threat', ['threat_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threat_action_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'blocked_threat_old', ['threat_id'], ['id'])

    with op.batch_alter_table('blocked_threat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocked_threat_ip_address'))
        batch_op.drop_index(batch_op.f('ix_blocked_threat_blocked_at'))

    with op.batch_alter_table('block_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_block_token_token'))
        batch_op.create_index(batch_op.f('ix_block_token_token'), ['token'], unique=False)

    op.create_table('threat_notification',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('website_id', sa.INTEGER(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=64), nullable=False),
    sa.Column('risk_category', sa.VARCHAR(length=20), nullable=False),
    sa.Column('summary', sa.VARCHAR(length=500), nullable=False),
    sa.Column('indicator', sa.VARCHAR(length=255), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('can_block', sa.BOOLEAN(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('verification_message', sa.VARCHAR(length=500), nullable=True),
    sa.Column('action_log', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['monitored_website.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('request_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('details', sa.VARCHAR(length=500), nullable=True),
    sa.Column('admin_notes', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_request_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('displayed_threat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_displayed_threat_threat_id'))
        batch_op.drop_index(batch_op.f('ix_displayed_threat_session_id'))
        batch_op.drop_index(batch_op.f('ix_displayed_threat_reported_at'))
        batch_op.drop_index(batch_op.f('ix_displayed_threat_ip_address'))
        batch_op.drop_index(batch_op.f('ix_displayed_threat_displayed_at'))

    op.drop_table('displayed_threat')
    with op.batch_alter_table('agent_enforcement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_enforcement_ip_address'))
        batch_op.drop_index(batch_op.f('ix_agent_enforcement_agent_id'))

    op.drop_table('agent_enforcement')
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_agent_id'))

    op.drop_table('agent')
    # ### end Alembic commands ###
