"""Add BlockToken model for persistent block tokens

Revision ID: add_block_token
Revises: 981676eda1ea
Create Date: 2026-01-04 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_block_token'
down_revision = '981676eda1ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('threat_type', sa.String(length=100), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_block_token_created_at', 'block_token', ['created_at'], unique=False)
    op.create_index('ix_block_token_expires_at', 'block_token', ['expires_at'], unique=False)
    op.create_index('ix_block_token_token', 'block_token', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_block_token_token', table_name='block_token')
    op.drop_index('ix_block_token_expires_at', table_name='block_token')
    op.drop_index('ix_block_token_created_at', table_name='block_token')
    op.drop_table('block_token')
    # ### end Alembic commands ###
